name: build_tweak

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  THEOS: /opt/theos

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo rm -rf ${{ env.THEOS }}
          sudo git clone --recursive https://github.com/theos/theos.git ${{ env.THEOS }}
          sudo chown -R $(id -u):$(id -g) ${{ env.THEOS }}
          echo "THEOS=${{ env.THEOS }}" >> $GITHUB_ENV
          echo "${{ env.THEOS }}/bin" >> $GITHUB_PATH

      - name: Install ldid
        run: |
          # ldid vositasini o'rnatish (signing uchun shart)
          brew install ldid

      - name: Setup SDK
        run: |
          rm -rf ${{ env.THEOS }}/sdks
          git clone https://github.com/theos/sdks.git ${{ env.THEOS }}/sdks

      - name: Setup Substrate Header
        run: |
          mkdir -p ${{ env.THEOS }}/include/Substrate
          curl -L https://raw.githubusercontent.com/theos/headers/master/CydiaSubstrate.h -o ${{ env.THEOS }}/include/Substrate/Substrate.h
          cp ${{ env.THEOS }}/include/Substrate/Substrate.h ${{ env.THEOS }}/include/CydiaSubstrate.h

      - name: Build Tweak
        run: |
          export THEOS=/opt/theos
          export PATH=$THEOS/bin:$PATH
          make clean
          make package FINALPACKAGE=1
        env:
          THEOS_DEVICE_IP: ""

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PUBG-Weapon-Tweak-Package
          path: packages/*.deb
